# Simple Arithmetic with NumPy

In this notebook, we explore how to perform **simple arithmetic operations in Python using NumPy**.

NumPy makes mathematical operations on large datasets extremely efficient. Unlike spreadsheet tools that can struggle with hundreds of thousands of rows, NumPy can handle **millions of values** quickly and reliably.

We will cover:
- Creating arrays and matrices
- Using random number generators
- Performing arithmetic operations on arrays
- Understanding element-wise computation

## Importing NumPy

We begin by importing NumPy and its random number generator. NumPy is the core library for numerical computation in Python.

In [1]:
import numpy as np
from numpy.random import randn

## Formatting Numeric Output

To improve readability, we limit numerical output to **two decimal places**. This is especially useful when working with floating-point values.

In [2]:
np.set_printoptions(precision=2)

## Creating Arrays

An **array** is a one-dimensional container that holds elements of the same data type.

A **matrix** is simply a two-dimensional array. In NumPy, both are created using the same `array()` function.

### Creating an Array from a Python List

Here, we create an array containing six integer values.

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

### Creating a Matrix (2D Array)

This matrix contains two rows and three columns. Notice how nested lists define rows.

In [4]:
b = np.array([[10, 20, 30], [40, 50, 60]])
b

array([[10, 20, 30],
       [40, 50, 60]])

## Creating Arrays via Assignment

NumPy can generate arrays programmatically using built-in functions, which is especially useful for simulations and data analysis.

### Random Numbers with a Fixed Seed

We set a **random seed** so that the generated values are reproducible.

`randn()` generates values from a **standard normal distribution**, producing both positive and negative numbers.

In [5]:
np.random.seed(25)
c = 36 * np.random.randn(6)
c

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

### Creating a Sequence of Numbers

`np.arange()` generates a sequence of evenly spaced values.

The ending value is **excluded** from the output.

In [6]:
d = np.arange(1, 35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

## Arithmetic Operations on Arrays

NumPy performs **element-wise arithmetic**, meaning operations are applied to corresponding elements in arrays.

### Scalar Multiplication

Each element in the array is multiplied by the scalar value.

In [7]:
a * 10

array([10, 20, 30, 40, 50, 60])

### Array Addition

Corresponding elements from each array are added together.

In [8]:
c + a

array([  9.22,  38.97, -27.23, -17.28, -29.45,  -2.  ])

### Array Subtraction

Each element in array `a` is subtracted from the corresponding element in array `c`.

In [9]:
c - a

array([  7.22,  34.97, -33.23, -25.28, -39.45, -14.  ])

### Element-wise Multiplication

Each value in `c` is multiplied by the corresponding value in `a`.

In [10]:
c * a

array([   8.22,   73.94,  -90.68,  -85.13, -172.24,  -48.02])

### Element-wise Division

Each element in `c` is divided by the corresponding element in `a`.

In [11]:
c / a

array([  8.22,  18.48, -10.08,  -5.32,  -6.89,  -1.33])

## Key Takeaways

- NumPy enables fast arithmetic on large datasets
- Operations are applied **element-wise** by default
- Arrays and matrices are both NumPy arrays
- This forms the foundation for statistical analysis and linear algebra